databases:
  - name: mydatabase
    plan: free
    databaseName: mydatabase
    user: myuser

services:
  - type: web
    plan: free
    name: todolist_nakazatotaichi_c
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn todoproject.todoproject.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mydatabase
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4